# Stack inputs
variable "stack_name" {
  description = "Name of the entire stack name"
}

variable "environment" {
  description = "Name of the environment. AlloweValues: prod/stage/uat/test/dev"
}

# Launch configuration
variable "launch_config_name" {
  description = "The  Prefix name of the launch configuration. Creates a unique name beginning with the specified prefix"
}

variable "image_id" {
  description = "The EC2 image ID to launch"
}

variable "instance_type" {
  description = "The size of instance to launch"
}

variable "keypair_name" {
  description = "The key name that should be used for the instance"
}

variable "volume_type" {
  description = "The type of volume. Can be standard, gp2, or io1. (Default: standard)"
}

variable "volume_size" {
  description = "The size of the volume in gigabytes"
}

# Autoscaling group
variable "autoscale_group_name" {
  description = "The name of the auto scaling group. By default generated by Terraform"
}

variable "subnets" {
  description = "A list of subnet IDs to launch resources in"
  type        = "list"
}

# Elastic Load Balancer
variable "lb_name" {
  description = "Name of the Load Balancer"
}

# Securtiy Groups
variable "vpc_id" {
  description = "Enter your VPC ID. eg: vpc-xxxxxx"
}

variable "your_source_ip" {
  description = "Enter your Source IP to whitelist. Eg: 44.32.45.67/32"
}

# Application related inputs
variable "application_port" {
  description = "Enter port of the application will be running under ASG"
}

variable "application_health_path" {
  description = "Enter your application path for ELB Health Checks. eg: '/', '/app/health', '/login'"
}
